<?php include 'includes/header.php';?>
<?php include 'includes/nav.php';?>
<?php include 'includes/hero.php';?>
<?php include 'includes/maincta.php';?>
<?php include 'includes/gettingstarted.php';?>
<?php include 'includes/cards.php';?>
<?php include 'includes/pricing.php';?>
<?php include 'includes/maincta.php';?>
<?php include 'includes/footer.php';?>
